const STATUS_FLOW = [
  "RUN SHEET",
  "EXECUTIVE ON THE WAY",
  "INCOMING MANIFEST",
  "PAYMENT PENDING",
  "PAYMENT REQUESTED",
  "PAYMENT DONE",
  "SHIPMENT CONNECTED",
];

export default STATUS_FLOW;
